#!/bin/bash
if [ ! -f /data/odoo/odoo-server.conf ]
  then
    echo "Error! odoo-server.conf not found!"
    exit 2
fi

declare -A conf

IFS="="
while read -r name value
do
  key=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
  val=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
  conf[$key]=$val
done < /data/odoo/odoo-server.conf

if [ ! -d /backup ]
  then
    mkdir /backup
fi
DATE=$(date +"%Y%m%d%H%M")
PWD=${conf[db_password]}
export PGPASSWORD=$PWD
echo "Backup of database..."
pg_dump -Fc -U ${conf[db_user]} -h ${conf[db_host]} $DBNAME > /backup/${DBNAME}_${DATE}.dump
echo "Database saved"

echo "Backup of files..."
tar -cvf /backup/${DBNAME}_${DATE}.tar /data/odoo
echo "Files saved"

